### PR TITLE
Bootstrap v3.3.7

### PR DESCRIPTION
**Pull request by Guite**
Raised max bound of jQuery dependency to v3, since Bootstrap v3.3.7 added support for jQuery 3.

### CODE REVIEW

**Comment by RobLoach** [comment]
Thank you, @Guite

**Comment by mrohnstock** [comment]
? 3.3.7 was already in branch `3` and got already tagged.

**Comment by Guite** [comment]
Sorry, didnt see that. `master` was on 3.3.6, hence I created the PR.

**Comment by mrohnstock** [comment]
Nothing to worry about. I think it would be appropriate to set branch `3` as current default-branch, instead of `master`, so this won't happen again (hopefully), until `4` is finally out.

**Comment by mrohnstock** [comment]
done. Thanks for your PR anyway :) :+1:

**Comment by RobLoach** [comment]
Oops! :ghost:  Thanks @mrohnstock

**Pull request merged**
